package message

import (
	"github.com/fqiyou/tools/foo/tools/logs"
	"testing"
)


func TestFormatMessageObject(t *testing.T) {
	log.NewLogger(10000)
	log.SetLevel(log.LevelDebug)
	log.EnableFuncCallDepth(true)

	log.SetLogger("console", "")

	//log.SetLogger("file", fmt.Sprintf(`{"filename":"logs.log","level":%d}`, log.LevelInfo))


	str := "MDAwMDAwNzJ7ImN0aW1lIjoxNTQzODQ0MDA4MjM5LCJpcCI6IjE4My4yMDUuMTQ4LjIzNCIsInByb2plY3QiOiJuZXdzZWFybl90ZXN0In1INHNJQUFBQUFBQUFBSFdUUFkvVE1Cakh2NHZic1kyY09IWFNicFY0dVVvTVNBaHVRTWh5a3llTnVjU0piS2VsVkxlQmhCQUxqREF4d2NMQWdJU0UrRGFVMDMwTG5yZ2NLb2piN04vei92ZmpoenNpbkpIWm1WQTVtWVZSR3NVc1pqUWVFYWRxUURLSldSckhsQ2JUSkVLNGJSRVNIMEZHcERWTkM4WXBzR1MySThNYzFpb0RuNG1FSWN0NG1LWlR5bFBPb3hDOWgzV1RRNFcyRzR2YjQva2RTbnZXV0xFR1kxV2owY0FEejJUYkhrRVdoQUVMdUU4Z2RWZkl6SFVHREZwTzdzOVBieTU2ZzgwTWdCWWxxRlhwL0J6VTUwYW51YzVOZ3kzaFBaUEdLQi81NCt1bi9idnZGeCsrN1Y5K1BJcmZxTnlWWkpaRWZYU2xsa2RkaEVFYWhDazU4TC9UYmxTaHlNeVpEdkNpd1cwYWN5WitLM1c2dU5VM0NCWFVvSjFvNWFxblAxKzh2bmo3N1BMTjUvMnI1NWZ2djZCRFo4RXNldDE0eUtlVVJoTmtXU20xOW9MSlF6RlJTd0ZtQTZxV2FNYjN3YklrNVJQR1U4b2ludERJNnl3TlNETERFWlFWVWpkNld5dTM5YUJGNGE0c21OMnNsRjZSR2I3clVqb0haaXNxV1BjRitjSEZxcnFycEd1TTkrbGo2dHdmaDNndWxMRk81Qkl6RjdLeWNENGl1YkpPNmN3ZE5vQ3hsQUtqTUU2bVVUYU9HVXpIc3VCeXZJeVRaUmdYakUyU0pYYnI1ZHo5UjlicjlMOTJPL3FBR2x6WjlOVXozTFVybUlPVHF2S3dEckttS1RzWlBGRjZBL29wSG5WUVFvVnJITndEYlJ0em90eGdZRUhuZzhFZkVEeVdhemtZeENIQktWRWk3ZnBXMi9ZdVB1Y0RCUnNzSklxcXM2WDQ1OWVrbEUvUEgvMENyOGpkekdVREFBQT0="
	str = ""

	a,err := FormatMessageObject(str)

	//util.ModelToString(a)
	log.Info(a)
	log.Info(err)
}
